server:
  port: 8080
  contextPath: /

spring:
  datasource:
    tomcat:
      max-wait: 5000
      max-active: 10
      test-on-borrow: true
    username: root
    password: toor
    url: jdbc:h2:file:./java_web_info
    driverClassName: org.h2.Driver
    liquibase:
      change-log: classpath:/migration/changelog.xml
      default-schema:
    first:
      username: root
      password: toor
      url: jdbc:h2:file:./first_database
      driver-class-name: org.h2.Driver
      liquibase:
        change-log: classpath:/migration/first/changelog.xml
        enabled: true
    second:
      username: root
      password: toor
      url: jdbc:h2:file:./second_database
      driver-class-name: org.h2.Driver
      liquibase:
        change-log: classpath:/migration/second/changelog.xml
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    mode: HTML
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  http:
    multipart:
      max-request-size: 5MB
      max-file-size: 12MB




liquibase:
  change-log: classpath:/migration/changelog.xml

JavaWebIntro:
  timezone: Europe/Moscow
